language: python
sudo: false
cache:
  pip: true
  directories:
    - $HOME/buildout-cache
python:
  - 2.7
install:
  - python bootstrap-buildout.py -c travis.cfg
  - bin/buildout -Nc travis.cfg buildout:eggs-directory=$HOME/buildout-cache/eggs buildout:download-cache=$HOME/buildout-cache/downloads
script:
  - bin/test
notifications:
  email:
    - maurits@vanrees.org
